[package]
name = "music_dowloader"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
serde = "1.0.228"
serde_json = "1.0.149"
slint = "1.15.0"
tokio = "1.49.0"
yt-dlp = "1.4.7"

[build-dependencies]
slint-build = "1.15"