[package]
name = "music_dowloader"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
log = "0.4.29"
slint = "1.14.1"
tokio = "1.49.0"
url = "2.5.8"
yt-dlp = "1.4.7"

[build-dependencies]
slint-build = "1.15.0"
